from .agent_tasks.plan_initializer import AgentPlanInitTaskConfigSelector
from .agent_tasks.plan_enhancer import AgentPlanEnhancingTaskConfigSelector
from .agent_tasks.enhance_classifier import AgentEnhanceClassifierTaskConfigSelector

PLANENH_MAIN_LOG_PATH =  'log/qa/kg_reasoner/medium/plan_enhancer/main'

DEFAULT_PLANINIT_TASK_CONFIG = AgentPlanInitTaskConfigSelector.select(base_config_version='v1')
DEFAUL_ENHCLASSIFY_TASK_CONFIG = AgentEnhanceClassifierTaskConfigSelector.select(base_config_version='v1')
DEFAULT_PLANENH_TASK_CONFIG = AgentPlanEnhancingTaskConfigSelector.select(base_config_version='v1')